# Tensorflow

Se trata de una plataforma de Machine Learning en python.Permite realizar lo siguiente:
- clasificacion de imagenes
- regresiones
- reforzamiento del aprendizaje
- procesamiento del lenguaje

Entre otros.

In [1]:
# Importar Tensorflow

import tensorflow as tf
# %tensorflow_version 2.x
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\alex_\\anaconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# Tensor

Un "tensor" es la generalizacion de vectores y matrices a dimensiones de gran tamaño.
Cada tensor representa una computacion parcialmente definida que eventualmente producirá un valor en especifico.

In [2]:
# Creat un Tensor

# Aqui para el tensor se especifica primero el valor y luego el tipo de dato
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
float = tf.Variable(3.848, tf.float64)

# Grado de un Tensor

Hace referencia al numero de dimensiones del tensor, el anterior fue un tensor de grado 0 conocido como escalar.

In [3]:
rank1_tensor = tf.Variable(["test", "Ok", "rafa"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"],["test", "rafa"]], tf.string)

PAra determinar el grado del tensor hacer lo siguiente:

In [4]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape del Tensor

Se refiere al numero de elementos de cada dimension, los devuelve en forma consecutiva, es decir para rank2_tensor, son 2 listas con 2 elementos cada una.

In [5]:
rank2_tensor.shape

TensorShape([2, 2])

In [6]:
# PAra cambiar el Shape del tensor hay que hacer lo siguiente:

tensor1 = tf.ones([1,2,3]) # Crea un tensor shape [1,2,3] de puros "1"s 
tensor2 = tf.reshape(tensor1, [2,3,1]) # Cambia el shape a [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 indica al tensor calcular el tamaño de la dimension faltante que acomplete el numero de elementos original

# El numero de elementos debe permanecer siendo el mismo 

In [10]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
